# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipull', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtentry',
            name='stop_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rtentry',
            name='vehicle_id',
            field=models.CharField(max_length=20),
        ),
    ]
