# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apipull', '0002_auto_20170830_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('connected', models.BooleanField(default=False)),
                ('http_status', models.CharField(default='', max_length=5)),
                ('json_status', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('agency_id', models.CharField(max_length=20)),
                ('route_short_name', models.CharField(max_length=20)),
                ('route_long_name', models.CharField(max_length=100)),
                ('route_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stop_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('stop_lon', models.DecimalField(decimal_places=6, max_digits=10)),
                ('location_type', models.CharField(max_length=1)),
                ('stop_code', models.CharField(max_length=10)),
                ('stop_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='rtentry',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='rtentry',
            name='route_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apipull.Route'),
        ),
        migrations.AlterField(
            model_name='rtentry',
            name='stop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apipull.Stop'),
        ),
        migrations.AddField(
            model_name='rtentry',
            name='call',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apipull.CallRecord'),
        ),
    ]
