# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipull', '0003_auto_20170901_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
